version: '3'
volumes:
  node_modules:
  postgres:

services:
  messenger:
    container_name: clinicx_messenger
    hostname: clinicx_messenger
    image: rabbitmq
    command: "rabbitmq-server"
    environment:
      - "RABBITMQ_DEFAULT_USER=clinicx"
      - "RABBITMQ_DEFAULT_PASS=clinicx"

  db:
    container_name: clinicx_db
    hostname: clinicx_db
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=clinicx"
      - "POSTGRES_USER=clinicx"
      - "POSTGRES_PASSWORD=clinicx"
    ports:
      - 54322:5432

  redis:
    image: redis
    container_name: clinicx_redis
    hostname: clinicx_redis

  primary:
    container_name: clinicx_primary
    hostname: clinicx-erp.local
    build:
      context: .
      dockerfile: Dockerfile
    image: clinicx
    env_file: .env
    command: >
      bash -c "
        sleep 5 &&
        pip install -r requirements.txt &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
      - ./etc/emails/:/tmp/emails/
    ports:
      - 8000:8000

  coturn:
    image: coturn/coturn:alpine
    command:
      - turnserver -v -L 0.0.0.0 \
        --server-name "rashcam" \
        --static-auth-secret="${TURN_SECRET}" \
        --realm="rashcam" \
        -p "3478" \
        --min-port "49152" \
        --max-port "65535" \
        --no-cli \
        --no-tls \
        --no-dtls \
        --no-stun
    tmpfs:
      - '/var/lib/coturn/'
    network_mode: host

  worker:
    container_name: clinicx_worker
    hostname: clinicx_worker
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: >
      bash -c "
        sleep 5 &&
        pip install -r requirements.txt &&
        celery --app=clinicx:celery_app worker -n %h
      "
    volumes:
      - .:/app
      - ./etc/emails/:/tmp/emails/
