version: '3.5'
volumes:
  postgres:

services:
  messenger:
    image: rabbitmq
    command: "rabbitmq-server"
    environment:
      - RABBITMQ_DEFAULT_USER=clinicx
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    restart: unless-stopped

  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=clinicx
      - POSTGRES_USER=clinicx
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped

  redis:
    image: redis
    restart: unless-stopped

  primary:
    build:
      context: .
      dockerfile: Dockerfile
    image: clinicx
    env_file: .env
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=messenger
      - POSTGRES_HOSTNAME=db
    command: >
      bash -c "
        sleep 5 &&
        pip install -r requirements.txt &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "5000:8000"
    restart: unless-stopped

  worker:
    image: clinicx_worker
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=messenger
      - POSTGRES_HOSTNAME=db
    command: >
      bash -c "
        sleep 5 &&
        pip install -r requirements.txt &&
        celery --app=clinicx:celery_app worker -n %h
      "
    restart: unless-stopped

  webapp:
    image: clinicx-ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "5001:3000"
    restart: unless-stopped
