# Generated by Django 3.2.7 on 2022-03-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='displayName',
            new_name='display_name',
        ),
    ]
