# Generated by Django 3.2.7 on 2022-03-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_displayname_user_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, default='General Physician', max_length=20, null=True),
        ),
    ]
