# Generated by Django 3.2.7 on 2022-03-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20220326_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clinic_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
