# Generated by Django 3.2.7 on 2022-03-26 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_doctorrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorrating',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.patientappointment'),
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
