# Generated by Django 3.2.7 on 2022-03-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_alter_clinictime_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientappointment',
            name='accepted',
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
