# Generated by Django 3.2.7 on 2022-03-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_auto_20220327_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientappointment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
